app/main_page/urls.py
from django.urls import path, include
from . import views

app_name = 'main_page'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
]

app/products_list/urls.py
from django.urls import path, include
from . import views

app_name = 'products_list'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
]

app/the_same_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lists/', include('products_list.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api_v1.urls')),
    path('', include('main_page.urls')),
]

# Если мы в режиме дебага
if settings.DEBUG:
    import debug_toolbar

    # Подключим дебагпанель
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    # Если мы в режиме дебага, то скажем django где брать загруженные файлы картинок и пр.
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    # Включить URL авторизации по умолчанию.
    # path('', include('django.contrib.auth.urls')),
    # Страница аутентификации
    path('login/', views.login, name='login'),
    # Страница регистрации.
    path('register/', views.register, name='register'),
    # Страница редактирования профиля
    path('edit/', views.edit, name='edit'),

    # Выход из профиля
    path('logout/', views.user_logout, name='logout')
]

app/products_list/models.py
from django.db import models
from django.contrib.auth.models import User


# from django.db import connection


class Product(models.Model):
    name = models.CharField(max_length=150)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name']
        db_table = "app_product"


class List(models.Model):
    title = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Список'
        verbose_name_plural = 'Списки'
        ordering = ['-created_at']
        db_table = "app_list"


class ProductInList(models.Model):
    name = models.ForeignKey(Product, on_delete=models.CASCADE)
    list = models.ForeignKey(List, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=150, blank=True)
    is_checked = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"List: {self.list.title}, Product: {self.name.name}"

    class Meta:
        verbose_name = 'Продукт в списке'
        verbose_name_plural = 'Продукт в списках'
        ordering = ['name']
        db_table = "app_product_in_list"

# ----------------------------------------------------------------


# def execute_my_sql_for_create_view_in_db():
#     """Создает представление app_all_product в базе данных
#     Для активации происходит выхов из Makefile:
#     	echo "from products_list.models import execute_my_sql_for_create_view_in_db;
#     	 execute_my_sql_for_create_view_in_db()" |
#     	 docker-compose exec -T web python manage.py shell
#     """
#
#     query = """CREATE VIEW app_all_product AS
#                     SELECT id, name from app_common_product
#                     UNION
#                     SELECT 10000+id as id, name from app_user_product"""
#     cursor = connection.cursor()
#     cursor.execute(query)
#
#
# class AllProduct(models.Model):
#     name = models.CharField(max_length=150)
#
#     class Meta:
#         managed = False
#         db_table = "app_all_product"

app/products_list/views.py
import json
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import List, Product, ProductInList


@login_required
def index(request):
    product_lists = List.objects.filter(owner=request.user)

    # Создадим словарь списков пользователя для последующей передачи json
    # data = {}
    # for some_list in product_lists:
    #     products = {}
    #     for some_set in some_list.products.all():
    #         products.update({
    #             some_set.pk: some_set.product_in_dict.name,
    #         })
    #     data.update({
    #         some_list.pk: {
    #             'name': some_list.title,
    #             'products': products,
    #         }
    #     })

    # data_dump = json.dumps(data)

    context = {
        "product_lists": product_lists,
        # 'data': data_dump,
    }

    return render(request, 'products_list/index.html', context=context)

app/products_list/templates/products_list/inc/_navbar.html
{% load static %}
<header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'main_page:index' %}"
               class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none"
               style="margin-right: 30px;">
                <img src="{% static 'images/logo_small.png' %}" alt="Тот самый список">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'products_list:index' %}" class="nav-link px-2 link-dark">Посмотреть мои
                    списки</a></li>
            </ul>

            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
                       id="dropdownUser1"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="{% url 'users:edit' %}">Профиль</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выход</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="col-md-3 text-end">
                    <a href="{% url 'users:login' %}" class="btn btn-outline-primary me-2">Войти</a>
                    <a href="{% url 'users:register' %}" class="btn btn-primary">Зарегистрироваться</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>